# Generated by Django 4.1.7 on 2023-02-14 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Paciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('DNI', models.IntegerField()),
                ('fecha_nac', models.DateField()),
                ('sexo', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Profesional',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('apellido', models.CharField(max_length=40)),
                ('mail', models.EmailField(max_length=254)),
                ('matricula', models.IntegerField()),
                ('profesion', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='TestCovid',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DNI_pac', models.IntegerField()),
                ('resultado', models.BooleanField()),
                ('estado', models.CharField(max_length=20)),
                ('profesional', models.CharField(max_length=50)),
                ('fecha', models.DateField()),
            ],
        ),
    ]
